### ISSUE TITLE
Directory can't be created

### ISSUE THREAD

**Issue by eddiezato** [EuFlo/sacd-ripper#3] opened 2020-10-03 08:09 UTC
Can't extract with _sacd_extract-0.3.9.3-88-win64_ version.
Original _sacd_extract_0.3.8_WIN32_ works fine.

```
PS D:\Downloads\Karajan Beethoven Symphonies (1963,2003)\Symphonie No.9> .\sacd_extract -P -i"Ludwig van Beethoven Symphony No.9.iso"

sacd_extract 0.3.9.3 enhanced by euflo ....starting!

Found configuration 'sacd_extract.cfg' file...
        Artist will be added in folder name (artist=0) no
        Performer will be added in filename of track (performer=0) no
        Padding-less (nopad=0) no
        Pauses included (pauses=0) no
        Concatenate (concatenate=0) no
        ID3tagV2.4 (id3tag = 4) yes

Disc Information:
        Version:  1.20
        Creation date: 2003-06-02
        Disc Catalog Number: 474 605-2
        Disc Category: General
        Disc Genre: Classical
        Locale: en, Code character set:[2], ISO-8859-1
        Title: Ludwig van Beethoven: Symphony no. 9
        Artist: Gundula Janowitz, soprano; Hilde Rossel-Majdan, contralto; Waldemar Kmentt, tenor; Walter Berry, baritone; Wiener Singverein (Chorus master: Reinhold Schmidt); Berliner Philharmoniker, Herbert von Karajan
        Publisher: 1963/2003 Deutsche Grammophon GmbH, Hamburg
        Copyright: 2003 Deutsche Grammophon GmbH, Hamburg

Album Information:
        Album Catalog Number: 474600-2
        Sequence Number: 5
        Set Size: 5
        Album Category: General
        Album Genre: Classical
        Title: Ludwig van Beethoven: The 9 Symphonies
        Artist: Gundula Janowitz, soprano; Hilde Rossel-Majdan, contralto; Waldemar Kmentt, tenor; Walter Berry, baritone; Wiener Singverein (Chorus master: Reinhold Schmidt); Berliner Philharmoniker, Herbert von Karajan
        Publisher: 1963/2003 Deutsche Grammophon GmbH, Hamburg
        Copyright: 2003 Deutsche Grammophon GmbH, Hamburg

Area count: 1
        Area Information [0]:

        Version:  1.20
        Track Count: 5
        Total play time: 67:05:00 [mins:secs:frames]
        Speaker config: 2 Channel
        Track list [0]:
                Title[0]: Symphony no. 9 in D minor, op. 125: 1. Allegro ma non troppo, un poco maestoso
                Performer[0]: Berliner Philharmoniker; Herbert von Karajan
                Composer[0]: Ludwig van Beethoven
                Track_Start_Time_Code: 00:02:00 [mins:secs:frames]
                Duration: 15:30:00 [mins:secs:frames]

                Title[1]: Symphony no. 9 in D minor, op. 125: 2. Molto vivace
                Performer[1]: Berliner Philharmoniker; Herbert von Karajan
                Composer[1]: Ludwig van Beethoven
                Track_Start_Time_Code: 15:32:00 [mins:secs:frames]
                Duration: 11:01:00 [mins:secs:frames]

                Title[2]: Symphony no. 9 in D minor, op. 125: 3. Adagio molto e cantabile
                Performer[2]: Berliner Philharmoniker; Herbert von Karajan
                Composer[2]: Ludwig van Beethoven
                Track_Start_Time_Code: 26:33:00 [mins:secs:frames]
                Duration: 16:26:00 [mins:secs:frames]

                Title[3]: Symphony no. 9 in D minor, op. 125: 4. Presto
                Performer[3]: Berliner Philharmoniker; Herbert von Karajan
                Composer[3]: Ludwig van Beethoven
                Track_Start_Time_Code: 42:59:00 [mins:secs:frames]
                Duration: 06:23:40 [mins:secs:frames]

                Title[4]: Symphony no. 9 in D minor, op. 125: (4. cont.) Presto - "O friends, no more these sounds!". Final chorus from Schiller's "Ode to Joy"
                Performer[4]: Gundula Janowitz, soprano; Hilde Rossel-Majdan, contralto; Waldemar Kmentt, tenor; Walter Berry, baritone; Vienna Singverein (Chorus master: Reinhold Schmid); Berliner Philharmoniker; Herbert von Karajan
                Composer[4]: Ludwig van Beethoven
                Track_Start_Time_Code: 49:22:40 [mins:secs:frames]
                Duration: 17:42:35 [mins:secs:frames]

        ISRC Track [0]:
          Country: DE, Owner: F05, Year: 62, Designation: 14981
        ISRC Track [1]:
          Country: DE, Owner: F05, Year: 62, Designation: 14982
        ISRC Track [2]:
          Country: DE, Owner: F05, Year: 62, Designation: 14983
        ISRC Track [3]:
          Country: DE, Owner: F05, Year: 62, Designation: 14984
        ISRC Track [4]:
          Country: DE, Owner: F05, Year: 62, Designation: 14985

Program terminates!

PS D:\Downloads\Karajan Beethoven Symphonies (1963,2003)\Symphonie No.9> .\sacd_extract -2 -e -c -C -i"Ludwig van Beethoven Symphony No.9.iso"

sacd_extract 0.3.9.3 enhanced by euflo ....starting!

Found configuration 'sacd_extract.cfg' file...
        Artist will be added in folder name (artist=0) no
        Performer will be added in filename of track (performer=0) no
        Padding-less (nopad=0) no
        Pauses included (pauses=0) no
        Concatenate (concatenate=0) no
        ID3tagV2.4 (id3tag = 4) yes


 Error: Ludwig van Beethoven The 9 Symphonies\Disc 5 directory can't be created.

Program terminates!
```

**Comment by NSP-0123456** [comment] 2020-10-08 07:53
**Additional comment :  Target system is windows platform 64bit using binaries from videohelps.** 
original 3.8 works fine...
enhanced by euflo 3.6.9.3- 63 - 71 - 75 works fine and able to create folder and files

Error after 3.9.3-75
--> 88, 87 Cannot create directory error
--> 84 same final error reported as not able to create file

**Comment by EuFlo** [comment] 2020-11-09 09:57
I can confirm the problem. 
When running in Windows cmd prompt and the output (-o) folder is not specified, the folder can't be created.
That is because in Windows we uses absolute paths.

As a rapid workaround: set the option -o to 'desired directory'
 Example:
 sacd_extract -s -i input.iso -o c:\outputfolder

Fixed in next version: 0.3.9.3-89

**Comment by NSP-0123456** [comment] 2020-11-09 10:51
workaround works fine if output folder -o is defined as full path only. Inside a batch file, you can use subst or %CD%  to replace current folder..

**Comment by NSP-0123456** [comment] 2020-11-09 11:06
-- error -- 
substituted folders do not work either  
i.e: subst o: .     and then using -o o:\

**Closed as completed** 2021-03-10 13:07 UTC
