### ISSUE TITLE
Directory can't be created

### ISSUE THREAD

**Issue by lupomeo** [EuFlo/sacd-ripper#4] opened 2020-10-19 08:08 UTC
Directory can't be created

**Comment by EuFlo** [comment] 2020-11-09 09:56
I can confirm the problem. 
When running in Windows cmd prompt and the output (-o) folder is not specified, the folder can't be created.
That is because in Windows we uses absolute paths.

As a rapid workaround: set the option -o to 'desired directory'
 Example:
 sacd_extract -s -i input.iso -o c:\outputfolder

Fixed in next version: 0.3.9.3-89

**Closed as completed** 2021-03-10 13:08 UTC
